core_config_version: 0
postgresql_config_version: 0
postgresql_password: "oO09vsiUxC62Gu7SpL7Cnr7LKYDP3egy"
postgresql_user: "getfamilyr"
disable_telemetry: true
postgresql_host: "dpg-ci8s8059aq0ee281harg-a"
postgresql_port: 5432
postgresql_database_name: "familyrdb_pwm9"
postgresql_connection_uri: "postgresql://getfamilyr:oO09vsiUxC62Gu7SpL7Cnr7LKYDP3egy@dpg-ci8s8059aq0ee281harg-a.ohio-postgres.render.com/familyrdb_pwm9"
